name = "door-lock-monitor"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[limits]
cpu_ms = 500

routes = [
  { pattern = "moztw.space/status", zone_name = "moztw.space" },
  { pattern = "moztw.space/api", zone_name = "moztw.space" },
]

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "LOCK_STATE"
id = "c643dd3deb164473ab7df3c79f4baeac"

[browser]
binding = "MYBROWSER"

[vars]
TELEGRAM_ENABLED = "true"        # 或 "false" 視你要不要開通知
TELEGRAM_OPEN_ANNOUNCEMENT_CHAT_ID = "@moztw_general"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1