name = "door-lock-monitor"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "LOCK_STATE"
id = "c643dd3deb164473ab7df3c79f4baeac"

[browser]
binding = "MYBROWSER"

[vars]
STATUS_URL = "https://biz.candyhouse.co"
LOCK_STATUS_SELECTOR = 'li.MuiListItem-root:has-text("工寮 Open Sensor") >> button.MuiIconButton-root'
STATUS_OPEN_REGEX = "(Open)"
STATUS_CLOSED_REGEX = "(Closed)"
TELEGRAM_ENABLED = "true"        # 或 "false" 視你要不要開通知
